export const GET_ALL_TRANSACTIONS = "GET_ALL_TRANSACTIONS";
export const GET_ONE_TRANSACTION = "GET_ONE_TRANSACTION";
export const DELETE_TRANSACTION = "DELETE_TRANSACTION";
export const TRANSACTION_ERROR = "TRANSACTION_ERROR";
