# We have 2 stage Test and Deploy
stages:
  - test
  - deploy

# Config cache
cache:
  paths:
    - node_modules/

# Test job
test:
  # Docker image
  image: node:14
  # Attach Test job to Test stage
  stage: test
  # Config to use GitLab Shared Runner with Executor Docker
  tags:
    - docker
  script:
    - echo "MYSQL_USERNAME"=$MYSQL_USERNAME > .env.test
    - echo "MYSQL_PASSWORD"=$MYSQL_PASSWORD >> .env.test
    - echo "MYSQL_DATABASE"=$MYSQL_DATABASE_TEST >> .env.test
    - echo "MYSQL_HOST"=$MYSQL_HOST >> .env.test
    - yarn install
    - NODE_ENV=test sequelize db:create # create database test
    - NODE_ENV=test sequelize db:migrate # create migration
    - NODE_ENV=test sequelize db:seed:all # seed all seeders data
    - yarn run test
    - NODE_ENV=test sequelize db:drop # drop database after testing
  # Defines the names of branches and tags the job runs for
  only:
    - ci-cd-sequelize

# Deploy job
deploy:
  type: deploy
  # Attach Deploy job to Deploy stage
  stage: deploy
  # Config to use our Runner with Executor Shell
  tags:
    - ci-cd-sequelize
  script:
    # Only copy changed files to project folder
    - cp -r -u * $PROJECT_DIR
    - cd $PROJECT_DIR
    - echo "MYSQL_USERNAME"=$MYSQL_USERNAME > .env.production
    - echo "MYSQL_PASSWORD"=$MYSQL_PASSWORD >> .env.production
    - echo "MYSQL_DATABASE"=$MYSQL_DATABASE_PRODUCTION >> .env.production
    - echo "MYSQL_HOST"=$MYSQL_HOST >> .env.production
    - yarn i
    - NODE_ENV=production sequelize db:create # create database test
    - NODE_ENV=production sequelize db:migrate # create migration
    # Restart NodeJS service
    - yarn run stop
    - yarn run start
  only:
    - ci-cd-sequelize
