# Use root/example as user/password credentials
version: "2.4"

services:
  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    volumes:
      - sequelize:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root

volumes:
  sequelize:
